{
    "name": "Dealer Financing",
    "summary": "Streamlines the financing application process for dealerships.",
    "category": "Finance/Custom Modules",
    "version": "1.0.0",
    "author": "ODOP Trainee",
    "maintainer": "Shikhar-GC",
    "depends": ["product", "contacts"],
    "data": [
        "security/dealer_financing_groups.xml",
        "security/ir.model.access.csv",
        "security/dealer_financing_security.xml",
        "views/loan_application_views.xml",
        "views/loan_application_tag_views.xml",
        "views/loan_application_document_type_views.xml",
        "views/res_partner_views.xml",
        "views/dealer_financing_menu.xml",
    ],
    "demo": [
        "demo/config_demo.xml",
        "demo/loan_demo.xml",
    ],
    "license": "OPL-1",
    "application": True,
}
